import type { NGOConfig } from '@/lib/types/portal'

export const orchestraConfig: NGOConfig = {
  id: 'orchestra',
  displayName: 'BEAM Orchestra Portal',
  shortName: 'BEAM Orchestra',
  description: 'Building Excellence in Arts and Music',
  homeSlides: [
    {
      id: 'watch-and-support',
      title: 'orchestra.BEAM',
      subtitle: 'Stream content, and more.',
      ctaLabel: 'Watch',
      ctaPath: '/viewer',
      imageSrc: '/images/orchestra/recording-sessions.svg',
      imageAlt: 'Audience and performers in a live recording showcase',
      audience: 'viewer',
      videoUrl:
        'https://firebasestorage.googleapis.com/v0/b/beam-orchestra-platform.firebasestorage.app/o/Black%20Diaspora%20Symphony%2Fstudio%2FSchumann%20-%20Adagio%20-%20Take%20II%20-%20Dec%205.mov?alt=media&token=34d0e14a-1721-4826-8e43-e3099d4a81c4',
    },
    {
      id: 'participant-pathway',
      title: 'orchestra.BEAM',
      subtitle: 'Become a Participant',
      ctaLabel: 'Join as Participant',
      ctaPath: '/join/participant',
      imageSrc: '/images/orchestra/chamber-submissions.svg',
      imageAlt: 'Participant pathway for sessions, cohorts, and performance opportunities',
      audience: 'participant_admin',
      videoUrl:
        'https://firebasestorage.googleapis.com/v0/b/beam-orchestra-platform.firebasestorage.app/o/Black%20Diaspora%20Symphony%2Finterviews%2FD.%20Hallmon%20Interview%20-%20Version%20I.mov?alt=media&token=e1d76347-cc8b-49f7-8268-189452051cf9',
    },
    {
      id: 'chamber-submissions',
      title: 'Chamber Submissions',
      subtitle: 'Submit repertoire and instrumentation requests for the next chamber cycle.',
      ctaLabel: 'Open Submissions',
      ctaPath: '/projects',
      imageSrc: '/images/orchestra/chamber-submissions.svg',
      imageAlt: 'Sheet music and stand lights in a chamber rehearsal hall',
      audience: 'participant_admin',
    },
    {
      id: 'recording-sessions',
      title: 'Recording Sessions',
      subtitle: 'Track upcoming recording blocks and reserve your seat in the studio.',
      ctaLabel: 'View Sessions',
      ctaPath: '/studio/recordings',
      imageSrc: '/images/orchestra/recording-sessions.svg',
      imageAlt: 'String section in a studio recording session',
      audience: 'participant_admin',
    },
    {
      id: 'mix-review',
      title: 'Mix Review',
      subtitle: 'Review draft mixes and leave concise feedback for engineering partners.',
      ctaLabel: 'Go to Dashboard',
      ctaPath: '/dashboard',
      imageSrc: '/images/orchestra/mix-review.svg',
      imageAlt: 'Audio timeline and waveform on a production monitor',
      audience: 'participant_admin',
    },
    {
      id: 'publishing-pathway',
      title: 'Publishing',
      subtitle: 'Join publishing projects with creative, production, and legal roles.',
      ctaLabel: 'Publishing Sign Up',
      ctaPath: '/publishing/signup',
      imageSrc: '/images/orchestra/submit-project.svg',
      imageAlt: 'Publishing sign-up pathway for project collaboration',
      audience: 'participant_admin',
    },
  ],
  recordingSlides: [
    {
      id: 'watch-live',
      title: 'Explore Performances',
      subtitle: 'Subscribers can stream live and archived sessions while following each cycle from rehearsal to stage.',
      ctaLabel: 'Open Viewer Area',
      ctaPath: '/viewer',
      imageSrc: '/images/orchestra/upcoming-sessions.svg',
      imageAlt: 'Public viewer previewing current performance releases',
      audience: 'viewer',
    },
    {
      id: 'book-beam-talent',
      title: 'Book BEAM Talent',
      subtitle: 'Use your monthly credits to request artists for community, nonprofit, and partner events.',
      ctaLabel: 'Start Booking Request',
      ctaPath: '/viewer/book',
      imageSrc: '/images/orchestra/submit-project.svg',
      imageAlt: 'Booking request form and event planning notes',
      audience: 'viewer',
    },
    {
      id: 'subscriber-credits',
      title: 'Subscriber Credits',
      subtitle: 'Track your credit balance and redeem access each month. BEAM participants retain free access.',
      ctaLabel: 'See Subscription Options',
      ctaPath: '/subscriber',
      imageSrc: '/images/orchestra/review-mixes.svg',
      imageAlt: 'Credit balance tile and subscription controls',
      audience: 'viewer',
    },
    {
      id: 'upcoming-sessions',
      title: 'View Upcoming Sessions',
      subtitle: 'See who is booked, where, and what each recording block covers.',
      ctaLabel: 'See My Schedule',
      ctaPath: '/dashboard',
      imageSrc: '/images/orchestra/upcoming-sessions.svg',
      imageAlt: 'Production calendar and orchestra call sheet',
      audience: 'participant_admin',
    },
    {
      id: 'submit-project',
      title: 'Submit a Project',
      subtitle: 'Pitch a recording initiative for BEAM players and partners.',
      ctaLabel: 'Submit Opportunity',
      ctaPath: '/projects',
      imageSrc: '/images/orchestra/submit-project.svg',
      imageAlt: 'Proposal document with orchestra branding',
      audience: 'participant_admin',
    },
    {
      id: 'review-mixes',
      title: 'Review Mixes',
      subtitle: 'Keep review cycles short with focused notes and approvals.',
      ctaLabel: 'Open Dashboard',
      ctaPath: '/dashboard',
      imageSrc: '/images/orchestra/review-mixes.svg',
      imageAlt: 'Headphones and waveform display for mix review',
      audience: 'participant_admin',
    },
  ],
  projects: [
    {
      id: 'city-symphony-series',
      name: 'City Symphony Series',
      summary: 'A recurring concert series featuring community and guest artists.',
      status: 'Active',
      href: '/projects/city-symphony-series',
    },
    {
      id: 'cross-arts-collab',
      name: 'Cross-Arts Collaboration',
      summary: 'Joint productions with dance and spoken-word partners.',
      status: 'Planning',
      href: '/projects/cross-arts-collab',
    },
    {
      id: 'youth-ensemble-lab',
      name: 'Youth Ensemble Lab',
      summary: 'Mentored side-by-side experiences for student performers.',
      status: 'In Review',
      href: '/projects/youth-ensemble-lab',
    },
  ],
}
