export interface ChecklistItem {
  id: string
  category: ChecklistCategory
  title: string
  description: string
  status: 'done' | 'in_progress' | 'pending'
  priority: 'critical' | 'high' | 'medium'
  assignee?: string
  targetPhase?: string
}

export type ChecklistCategory =
  | 'legal'
  | 'fleet_contract'
  | 'cohort'
  | 'academic'
  | 'partners'
  | 'infrastructure'
  | 'financial'
  | 'tech'

export interface CategoryMeta {
  id: ChecklistCategory
  name: string
  icon: string
  color: string
  description: string
}

export const CHECKLIST_CATEGORIES: CategoryMeta[] = [
  {
    id: 'legal',
    name: 'Legal & Compliance',
    icon: 'ShieldCheck',
    color: '#3B82F6',
    description: 'Corporate filings, DOT/FMCSA registrations, insurance, and municipal operating permits.',
  },
  {
    id: 'fleet_contract',
    name: 'RAG Fleet Contract',
    icon: 'FileText',
    color: '#8B5CF6',
    description: 'RAG ↔ BEAM intercompany agreement, fleet maintenance SLAs, lease, and dispatch terms.',
  },
  {
    id: 'cohort',
    name: 'Cohort & Workforce',
    icon: 'Users',
    color: '#10B981',
    description: 'Driver operator pledges, mechanic apprentice onboarding, safety training, and certifications.',
  },
  {
    id: 'academic',
    name: 'Academic Partnerships',
    icon: 'GraduationCap',
    color: '#F59E0B',
    description: 'University research corridors, BYD/NIO academic import pathways, and student research telemetry.',
  },
  {
    id: 'partners',
    name: 'Anchor Partners',
    icon: 'Handshake',
    color: '#EC4899',
    description: 'Parts store anchor MOU, car rental cousin fleet MOU, dispatch partner agreements, and dealerships.',
  },
  {
    id: 'infrastructure',
    name: 'Physical Infrastructure',
    icon: 'Wrench',
    color: '#6366F1',
    description: 'Vehicle depot staging, Level 2/3 charging access, maintenance bays, and diagnostic toolchains.',
  },
  {
    id: 'financial',
    name: 'Financial & Grants',
    icon: 'DollarSign',
    color: '#00D4AA',
    description: 'FTA 5310/5311 grant readiness, family investment fund, Stripe accounts, and city gap service billing.',
  },
  {
    id: 'tech',
    name: 'Web, Tech & Telemetry',
    icon: 'Cpu',
    color: '#F0A500',
    description: 'Truth dashboard, mobile progressive wizard, live dispatch ledger, and Firebase auth infrastructure.',
  },
]

export const DEFAULT_CHECKLIST_ITEMS: ChecklistItem[] = [
  // 1. Legal & Compliance (8 items)
  {
    id: 'leg-01',
    category: 'legal',
    title: '501(c)(3) Operating Standing Verified',
    description: 'Confirm BEAM Think Tank NGO status and certificate of good standing with state registry.',
    status: 'done',
    priority: 'critical',
    targetPhase: 'Phase 0',
  },
  {
    id: 'leg-02',
    category: 'legal',
    title: 'USDOT & FMCSA Intrastate Registration',
    description: 'File Form MCS-150 for motor carrier identification for non-profit community transit.',
    status: 'in_progress',
    priority: 'critical',
    targetPhase: 'Phase 1',
  },
  {
    id: 'leg-03',
    category: 'legal',
    title: 'Commercial Fleet Auto Liability Policy',
    description: 'Secure $1M/$2M commercial auto insurance quote covering dual non-profit / contractor operation.',
    status: 'pending',
    priority: 'critical',
    targetPhase: 'Phase 2',
  },
  {
    id: 'leg-04',
    category: 'legal',
    title: 'Lake County Municipal Transit Permit',
    description: 'File intent for microtransit gap operations with Lake County Board of Commissioners.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'leg-05',
    category: 'legal',
    title: 'Milwaukee Pilot Area Operating Agreement',
    description: 'Draft draft municipal operating memorandum for central city corridor transit routes.',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 1',
  },
  {
    id: 'leg-06',
    category: 'legal',
    title: 'Spirit Airlines Bankruptcy Claim Filing',
    description: 'Review SDNY Case 25-11897 docket for ground support equipment & airport shuttle liquidation.',
    status: 'in_progress',
    priority: 'medium',
    targetPhase: 'Phase 1',
  },
  {
    id: 'leg-07',
    category: 'legal',
    title: 'Volunteer & Driver Liability Waivers',
    description: 'Create legally vetted driver assumption of risk and liability release documents.',
    status: 'done',
    priority: 'high',
    targetPhase: 'Phase 0',
  },
  {
    id: 'leg-08',
    category: 'legal',
    title: 'ADA Title III Compliance Review',
    description: 'Verify wheelchair accessibility and service animal accommodation standards for transit fleet.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },

  // 2. RAG Fleet Contract (8 items)
  {
    id: 'flt-01',
    category: 'fleet_contract',
    title: 'Master RAG ↔ BEAM Intercompany Agreement',
    description: 'Formalize equipment lease, tech platform licensing, and shared overhead allocation.',
    status: 'done',
    priority: 'critical',
    targetPhase: 'Phase 0',
  },
  {
    id: 'flt-02',
    category: 'fleet_contract',
    title: 'Fleet Maintenance Service Level Agreement (SLA)',
    description: 'Establish preventive maintenance schedule (5,000 mi oil, brake inspections, tire rotations).',
    status: 'in_progress',
    priority: 'critical',
    targetPhase: 'Phase 1',
  },
  {
    id: 'flt-03',
    category: 'fleet_contract',
    title: 'RAG Transit 1 & 2 Vehicle Title & Lien Transfer',
    description: 'Review title status and lease terms for Ford Transit passenger and cargo units.',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'flt-04',
    category: 'fleet_contract',
    title: 'Fuel & Energy Reimbursement Schedule',
    description: 'Establish automated per-mile fuel surcharge and EV charging reimbursement rate table.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },
  {
    id: 'flt-05',
    category: 'fleet_contract',
    title: 'Driver Sub-Contractor Compensation Schedule',
    description: 'Determine hourly sweat-equity credits and BEAM Coin distribution rate per completed dispatch.',
    status: 'done',
    priority: 'high',
    targetPhase: 'Phase 0',
  },
  {
    id: 'flt-06',
    category: 'fleet_contract',
    title: 'Telematics & Hardware Installation Rights',
    description: 'Grant BEAM rights to install OBD-II GPS trackers and dual dash-cams on all RAG vehicles.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },
  {
    id: 'flt-07',
    category: 'fleet_contract',
    title: 'RAG ProMaster Cargo Van Commercial Endorsement',
    description: 'Update cargo van commercial endorsement for municipal food & pharmacy delivery routes.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'flt-08',
    category: 'fleet_contract',
    title: 'Quarterly Fleet Audit & Deprecation Schedule',
    description: 'Set up depreciation calculations and vehicle condition reporting standards.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 3',
  },

  // 3. Cohort & Workforce (8 items)
  {
    id: 'coh-01',
    category: 'cohort',
    title: 'Driver Intake Wizard Deployed',
    description: 'Interactive progressive disclosure wizard live on transportation.beamthinktank.space.',
    status: 'done',
    priority: 'critical',
    targetPhase: 'Phase 0',
  },
  {
    id: 'coh-02',
    category: 'cohort',
    title: 'Motor Vehicle Record (MVR) Background Check Integration',
    description: 'Configure Checkr or Turn background check workflow for clean driver records (3-year lookback).',
    status: 'in_progress',
    priority: 'critical',
    targetPhase: 'Phase 1',
  },
  {
    id: 'coh-03',
    category: 'cohort',
    title: 'Mechanic Apprentice Cohort Curriculum',
    description: 'Assemble 6-week hands-on syllabus: EV powertrain, brake servicing, and fleet telemetry diagnostics.',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'coh-04',
    category: 'cohort',
    title: 'First 10 Community Driver Pledges Logged',
    description: 'Collect initial batch of verified driver seat reservations across Milwaukee and Leesburg hubs.',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 1',
  },
  {
    id: 'coh-05',
    category: 'cohort',
    title: 'DOT Medical Examiner Certificate Protocols',
    description: 'Identify partner urgent care clinic for discounted CDL and passenger endorsement physicals.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },
  {
    id: 'coh-06',
    category: 'cohort',
    title: 'Operator Safety & De-escalation Training Module',
    description: 'Build passenger safety, conflict resolution, and emergency roadside procedure handbook.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'coh-07',
    category: 'cohort',
    title: 'Participant Digital Workspace & Profile Portal',
    description: 'Live profile tracking sweat-equity hours, BEAM Coins, and assigned fleet units.',
    status: 'done',
    priority: 'high',
    targetPhase: 'Phase 0',
  },
  {
    id: 'coh-08',
    category: 'cohort',
    title: 'Student & Youth Flight Drone Corridors',
    description: 'Draft FAA Part 107 prep track for drone logistics and aerial corridor telemetry.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 3',
  },

  // 4. Academic Partnerships (8 items)
  {
    id: 'aca-01',
    category: 'academic',
    title: 'University Research Corridor Pitch Deck',
    description: 'Create university proposal: zero-emission transit laboratory and student mobility data rights.',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 1',
  },
  {
    id: 'aca-02',
    category: 'academic',
    title: 'BYD / NIO Academic Import Regulatory Analysis',
    description: 'Document 49 CFR Part 591 research exemption for testing non-certified electric vehicles.',
    status: 'done',
    priority: 'high',
    targetPhase: 'Phase 0',
  },
  {
    id: 'aca-03',
    category: 'academic',
    title: 'UWM / Marquette Engineering Outreach',
    description: 'Initial meeting with civil and mechanical engineering departments for telemetry sensors.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },
  {
    id: 'aca-04',
    category: 'academic',
    title: 'Open Transit Data Specification (GTFS / GBFS)',
    description: 'Setup GTFS real-time schedule feed generator for university transit app integration.',
    status: 'in_progress',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },
  {
    id: 'aca-05',
    category: 'academic',
    title: 'Student Capstone Project Sponsor Agreements',
    description: 'Draft project charters for fall/spring senior design student engineering cohorts.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },
  {
    id: 'aca-06',
    category: 'academic',
    title: 'Telemetry Research Data Privacy Framework',
    description: 'Ensure anonymization protocols for commuter mobility logs and passenger heatmaps.',
    status: 'done',
    priority: 'high',
    targetPhase: 'Phase 0',
  },
  {
    id: 'aca-07',
    category: 'academic',
    title: 'Lake-Sumter State College (Leesburg) Campus Outreach',
    description: 'Propose direct commuter shuttle connecting downtown Leesburg to LSSC campus.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'aca-08',
    category: 'academic',
    title: 'Published Academic Transit Case Study',
    description: 'Author joint white paper on microtransit efficiency vs fixed-route 60-minute headway deficits.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 3',
  },

  // 5. Anchor Partners (8 items)
  {
    id: 'par-01',
    category: 'partners',
    title: "Eric's Mom Auto Parts Store MOU",
    description: 'Sign wholesale parts and supplies purchasing agreement (commercial account discount).',
    status: 'in_progress',
    priority: 'critical',
    targetPhase: 'Phase 1',
  },
  {
    id: 'par-02',
    category: 'partners',
    title: 'Car Rental Cousin Fleet Surplus MOU',
    description: 'Sign MOU for access to idle weekend / seasonal vehicle inventory for on-demand transit.',
    status: 'in_progress',
    priority: 'critical',
    targetPhase: 'Phase 1',
  },
  {
    id: 'par-03',
    category: 'partners',
    title: 'Dispatch Cousin Operations MOU',
    description: 'Establish backup dispatch routing and driver re-allocation partnership.',
    status: 'in_progress',
    priority: 'critical',
    targetPhase: 'Phase 1',
  },
  {
    id: 'par-04',
    category: 'partners',
    title: 'Local Dealership Floor Plan Pitch (/dealer)',
    description: 'Deploy /dealer page targeting aged inventory ($7.90/day floor plan cost offset).',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 1',
  },
  {
    id: 'par-05',
    category: 'partners',
    title: 'EV Fleet Manufacturer Direct Pipeline (/manufacturer)',
    description: 'Deploy /manufacturer landing page for EV demo units and test fleet allocation.',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 1',
  },
  {
    id: 'par-06',
    category: 'partners',
    title: 'Lake County Food Bank Logistics Agreement',
    description: 'Execute service contract for weekend scheduled food pantry deliveries to transit deserts.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'par-07',
    category: 'partners',
    title: 'Senior Living Center Transport Concierge',
    description: 'Establish recurring weekday medical appointment shuttle with Lake County facilities.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'par-08',
    category: 'partners',
    title: 'MKE Mitchell Airport Ground Gate Logistics',
    description: 'Inquire on ground transportation commercial staging permit for clean-energy shuttles.',
    status: 'in_progress',
    priority: 'medium',
    targetPhase: 'Phase 1',
  },

  // 6. Physical Infrastructure (8 items)
  {
    id: 'inf-01',
    category: 'infrastructure',
    title: 'Base Depot Staging Lot Leased',
    description: 'Secure gated, secure parking for 4–8 vehicles with overnight floodlighting.',
    status: 'pending',
    priority: 'critical',
    targetPhase: 'Phase 2',
  },
  {
    id: 'inf-02',
    category: 'infrastructure',
    title: 'Level 2 EV Charging Bank Access',
    description: 'Identify or install 2× 48A Level 2 chargers with dedicated sub-metering.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'inf-03',
    category: 'infrastructure',
    title: 'Mechanic Bay & Hydraulic Lift Access',
    description: 'Negotiate weekend/evening shared bay lease with partner auto repair facility.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'inf-04',
    category: 'infrastructure',
    title: 'Fleet Diagnostic Scanner & Tool Kit',
    description: 'Purchase Autel or Snap-on bi-directional OBD scanner, EV insulated tool kit, and floor jacks.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },
  {
    id: 'inf-05',
    category: 'infrastructure',
    title: 'Key Storage & Electronic Lockbox',
    description: 'Install smart PIN-coded key locker with automated audit trail for vehicle checkout.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },
  {
    id: 'inf-06',
    category: 'infrastructure',
    title: 'Mobile Emergency Roadside Kit in Every Van',
    description: 'Equip vans with jump packs, tire inflators, first aid kits, AED, and road flares.',
    status: 'pending',
    priority: 'critical',
    targetPhase: 'Phase 2',
  },
  {
    id: 'inf-07',
    category: 'infrastructure',
    title: 'Commercial Vehicle Exterior Decals & Signage',
    description: 'Design and apply high-visibility reflective BEAM Transportation livery & USDOT numbers.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'inf-08',
    category: 'infrastructure',
    title: 'Solar Canopy & Microgrid Staging Assessment',
    description: 'Evaluate feasibility of off-grid solar charging canopy for depot resilience.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 3',
  },

  // 7. Financial & Grants (8 items)
  {
    id: 'fin-01',
    category: 'financial',
    title: 'Stripe Billing & Express Connect Setup',
    description: 'Configure automated passenger fare collection, subscription tiers, and driver payouts.',
    status: 'done',
    priority: 'critical',
    targetPhase: 'Phase 0',
  },
  {
    id: 'fin-02',
    category: 'financial',
    title: 'FTA Section 5310 Grant Application (Mobility for Seniors)',
    description: 'Prepare capital vehicle acquisition grant under Formula Grants for Enhanced Mobility.',
    status: 'in_progress',
    priority: 'critical',
    targetPhase: 'Phase 2',
  },
  {
    id: 'fin-03',
    category: 'financial',
    title: 'FTA Section 5311 Rural Transit Grant Readiness',
    description: 'Audit Lake County rural corridor eligibility for operating assistance funding.',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'fin-04',
    category: 'financial',
    title: '$25,000 Family Seed Investment Pool',
    description: 'Execute seed promissory notes / capital contribution agreements for initial vehicle down payment.',
    status: 'in_progress',
    priority: 'critical',
    targetPhase: 'Phase 1',
  },
  {
    id: 'fin-05',
    category: 'financial',
    title: 'VC414 Introduction via Jordan',
    description: 'Deliver executive deck on microtransit workforce flywheel and municipal revenue model.',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 1',
  },
  {
    id: 'fin-06',
    category: 'financial',
    title: 'Transit Truth Consulting Service ($2,500/report)',
    description: 'Package LakeXpress gap audit into sellable consulting product for other transit deserts.',
    status: 'done',
    priority: 'high',
    targetPhase: 'Phase 0',
  },
  {
    id: 'fin-07',
    category: 'financial',
    title: 'Municipal Transit Gap Service Contract LOI ($150K–$300K)',
    description: 'Submit formal proposal to Lake County BCC for night/weekend microtransit supplement.',
    status: 'pending',
    priority: 'critical',
    targetPhase: 'Phase 2',
  },
  {
    id: 'fin-08',
    category: 'financial',
    title: 'QuickBooks / Ledger Chart of Accounts for Transit',
    description: 'Segment fleet depreciation, fuel, driver stipends, and repair expenses by vehicle VIN.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },

  // 8. Web, Tech & Telemetry (8 items)
  {
    id: 'tec-01',
    category: 'tech',
    title: 'Leesburg Truth Dashboard Live (/dashboard/leesburg-fl)',
    description: 'Full public evidentiary dashboard with NTD ID 40158 stats, gap analysis, and incident log.',
    status: 'done',
    priority: 'critical',
    targetPhase: 'Phase 0',
  },
  {
    id: 'tec-02',
    category: 'tech',
    title: 'Implementation Timeline Deployed (/admin/implementation-timeline)',
    description: '4 interactive tabs covering full phases, this week actions, gate milestones, and money streams.',
    status: 'done',
    priority: 'critical',
    targetPhase: 'Phase 0',
  },
  {
    id: 'tec-03',
    category: 'tech',
    title: 'Admin Launch Checklist Portal (/admin/launch-checklist)',
    description: '64-item interactive tracker with filtering, priority badges, and persistent progress.',
    status: 'done',
    priority: 'critical',
    targetPhase: 'Phase 1',
  },
  {
    id: 'tec-04',
    category: 'tech',
    title: 'Dedicated Firebase Project (beam-transportation)',
    description: 'Provisioned beam-transportation with isolated auth, Firestore, and storage rules.',
    status: 'done',
    priority: 'critical',
    targetPhase: 'Phase 1',
  },
  {
    id: 'tec-05',
    category: 'tech',
    title: 'Live GPS Telemetry & Map Tracking Integration',
    description: 'Real-time vehicle position map using Google Maps Platform and GPS tracker webhooks.',
    status: 'in_progress',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'tec-06',
    category: 'tech',
    title: 'Progressive Web App (PWA) Driver Dispatch Screen',
    description: 'Mobile offline-capable driver view for accepting rides and logging passenger pickups.',
    status: 'pending',
    priority: 'high',
    targetPhase: 'Phase 2',
  },
  {
    id: 'tec-07',
    category: 'tech',
    title: 'Automated SMS Alerts via Twilio',
    description: 'Notify passengers when shuttle is 5 minutes away and dispatch emergency driver broadcasts.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 2',
  },
  {
    id: 'tec-08',
    category: 'tech',
    title: 'Public Status & Route Schedule API',
    description: 'REST and GraphQL endpoint exposing live vehicle status and scheduled corridor stops.',
    status: 'pending',
    priority: 'medium',
    targetPhase: 'Phase 3',
  },
]
